language: go
os: osx
before_install:
  - brew update
  - brew install hugo
  - rm .git/objects/pack/pack-4ac0747e0ae7cdf0a606e1d806fa3c4af0761ddc.pack
install:
  - hugo -d dist/
script: bash ./deploy.sh
env:
  global:
    - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/GEEE-UEFS/blog.git
